#!/bin/bash

DEVICE="/dev/video0"
if [[ -n $1 ]]; then
        DEVICE="$1"
fi

OUTPUT="output.mpg";
if [[ -n $2 ]]; then
        OUTPUT="$2";
else
        if [ -f "$OUTPUT" ]; then 
                for x in {1..1000}; do
                        X="output$x.mpg"
                        if [[ ! -f $X ]]; then
                                OUTPUT=$X;
                                break;
                        fi
                done;
        fi
fi

echo $OUTPUT $DEVICE;

ffmpeg -f video4linux2 -s 640x480 -i $DEVICE $OUTPUT
